name: @name@
version: @version@
main: click.seichi.gigantic.Gigantic
api-version: 1.14
depend: [ProtocolLib]
load: STARTUP


commands:
  will:
    description: This is will command.
    usage: /will <willName>
    aliases: [will]
    default: op
    permission: gigantic.will
    permission-message: You don't have <permission>
  vote:
    description: This is vote command.
    usage: /vote <playername> <num>
    aliases: [vote]
    default: op
    permission: gigantic.vote
    permission-message: You don't have <permission>
  donate:
    description: This is donate command.
    usage: /donate <playername> <num>
    aliases: [donate]
    default: op
    permission: gigantic.donate
    permission-message: You don't have <permission>
  tell:
    description: This is tell command.
    usage: /w <playername> <msg>
    aliases: [w,msg]
    default: default
    permission: gigantic.tell
    permission-message: You don't have <permission>
  reply:
    description: This is reply command.
    usage: /r <msg>
    aliases: [r]
    default: default
    permission: gigantic.reply
    permission-message: You don't have <permission>
  live:
    description: This is live command.
    usage: /live <on/off>
    aliases: [l,live]
    default: op
    permission: gigantic.live
    permission-message: You don't have <permission>
  home:
    description: This is home command.
    usage: /home <id> <name>
    aliases: [home,h]
    default: default
    permission: gigantic.home
    permission-message: You don't have <permission>
  now:
    description: This is datetime command.
    usage: /now
    aliases: [n]
    default: op
    permission: gigantic.now
    permission-message: You don't have <permission>